language: perl
perl:
  - "5.10"
  - "5.20"
  - "5.30"
sudo: false
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
install:
  - cpan-install --deps
script:
  - prove -l -j$(test-jobs) $(test-files)
